In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt #from matplotlib import pyplot

In [2]:
datos = pd.read_csv("../datos/WhiskyConFaltantes.csv") #levantamos el archivo a un dataframe

In [3]:
datos

    id_Whisky  Precio  Malta   Categoria  Anejamiento  Calidad
0           1    70.0   20.0        Lujo          5.0        3
1           2    60.0   20.0        Lujo          5.0        2
2           3    65.0   20.0        Lujo          7.5        2
3           4    74.0   25.0        Lujo          NaN        2
4           5    70.0   25.0        Lujo         12.0        3
5           6     NaN   30.0        lujo          5.0        0
6           7    70.0   30.0        Lujo          8.0        0
7           8    55.0   30.0        Lujo          5.0        2
8           9    77.0   30.0        lujo          5.5        0
9          10    93.0   30.0        Lujo         12.0        0
10         11    82.0   30.0        Lujo         12.0        2
11         12    73.0   33.0    Estandar          6.5        1
12         13    62.0   33.0    Estandar          8.0        3
13         14    87.0   33.0    Estandar         12.0        3
14         15    78.0   35.0    Estandar         10.0        2
15         16    73.0   40.0    Estandar         10.5        4
16         17    87.0   40.0    Estandar          8.5        2
17         18    80.0   40.0         NaN          8.5        2
18         19    85.0   40.0    Estandar          9.5        2
19         20    87.0   40.0    Estandar          8.5        4
20         21    80.0   40.0    Estandar          9.5        2
21         22    83.0   40.0    Estandar          9.5        1
22         23    90.0   40.0    Estandar         12.5        2
23         24   110.0   40.0    Estandar         12.0        3
24         25    87.0   40.0    Estandar          5.5        2
25         26   113.0   45.0         NaN         12.0        4
26         27    96.0   45.0    Estandar         12.0        3
27         28    82.0   45.0    Estandar         12.0        3
28         29   127.0  100.0  Pura_Malta          8.5        4
29         30   160.0  100.0  Pura_Malta         12.0        3
30         31    90.0  100.0  Pura_Malta          NaN        4
31         32     NaN  100.0  Pura_Malta         12.0        2
32         33   100.0  100.0  Pura_Malta         10.0        3
33         34   100.0    NaN  Pura_Malta         11.0        3
34         35    95.0  100.0  Pura_Malta         12.0        0

In [4]:
datos['Precio'].fillna(datos['Precio'].mean(),inplace=True)

C:\Users\martb\AppData\Local\Temp\ipykernel_23068\3465562981.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  datos['Precio'].fillna(datos['Precio'].mean(),inplace=True)

In [5]:
categorias = datos['Categoria'].value_counts()
datos['Categoria'].replace('lujo','Lujo',inplace=True)
datos

C:\Users\martb\AppData\Local\Temp\ipykernel_23068\430361757.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  datos['Categoria'].replace('lujo','Lujo',inplace=True)

    id_Whisky      Precio  Malta   Categoria  Anejamiento  Calidad
0           1   70.000000   20.0        Lujo          5.0        3
1           2   60.000000   20.0        Lujo          5.0        2
2           3   65.000000   20.0        Lujo          7.5        2
3           4   74.000000   25.0        Lujo          NaN        2
4           5   70.000000   25.0        Lujo         12.0        3
5           6   86.090909   30.0        Lujo          5.0        0
6           7   70.000000   30.0        Lujo          8.0        0
7           8   55.000000   30.0        Lujo          5.0        2
8           9   77.000000   30.0        Lujo          5.5        0
9          10   93.000000   30.0        Lujo         12.0        0
10         11   82.000000   30.0        Lujo         12.0        2
11         12   73.000000   33.0    Estandar          6.5        1
12         13   62.000000   33.0    Estandar          8.0        3
13         14   87.000000   33.0    Estandar         12.0        3
14         15   78.000000   35.0    Estandar         10.0        2
15         16   73.000000   40.0    Estandar         10.5        4
16         17   87.000000   40.0    Estandar          8.5        2
17         18   80.000000   40.0         NaN          8.5        2
18         19   85.000000   40.0    Estandar          9.5        2
19         20   87.000000   40.0    Estandar          8.5        4
20         21   80.000000   40.0    Estandar          9.5        2
21         22   83.000000   40.0    Estandar          9.5        1
22         23   90.000000   40.0    Estandar         12.5        2
23         24  110.000000   40.0    Estandar         12.0        3
24         25   87.000000   40.0    Estandar          5.5        2
25         26  113.000000   45.0         NaN         12.0        4
26         27   96.000000   45.0    Estandar         12.0        3
27         28   82.000000   45.0    Estandar         12.0        3
28         29  127.000000  100.0  Pura_Malta          8.5        4
29         30  160.000000  100.0  Pura_Malta         12.0        3
30         31   90.000000  100.0  Pura_Malta          NaN        4
31         32   86.090909  100.0  Pura_Malta         12.0        2
32         33  100.000000  100.0  Pura_Malta         10.0        3
33         34  100.000000    NaN  Pura_Malta         11.0        3
34         35   95.000000  100.0  Pura_Malta         12.0        0

In [6]:
datos['Categoria']=datos['Categoria'].replace('lujo','Lujo')

In [7]:
datos

    id_Whisky      Precio  Malta   Categoria  Anejamiento  Calidad
0           1   70.000000   20.0        Lujo          5.0        3
1           2   60.000000   20.0        Lujo          5.0        2
2           3   65.000000   20.0        Lujo          7.5        2
3           4   74.000000   25.0        Lujo          NaN        2
4           5   70.000000   25.0        Lujo         12.0        3
5           6   86.090909   30.0        Lujo          5.0        0
6           7   70.000000   30.0        Lujo          8.0        0
7           8   55.000000   30.0        Lujo          5.0        2
8           9   77.000000   30.0        Lujo          5.5        0
9          10   93.000000   30.0        Lujo         12.0        0
10         11   82.000000   30.0        Lujo         12.0        2
11         12   73.000000   33.0    Estandar          6.5        1
12         13   62.000000   33.0    Estandar          8.0        3
13         14   87.000000   33.0    Estandar         12.0        3
14         15   78.000000   35.0    Estandar         10.0        2
15         16   73.000000   40.0    Estandar         10.5        4
16         17   87.000000   40.0    Estandar          8.5        2
17         18   80.000000   40.0         NaN          8.5        2
18         19   85.000000   40.0    Estandar          9.5        2
19         20   87.000000   40.0    Estandar          8.5        4
20         21   80.000000   40.0    Estandar          9.5        2
21         22   83.000000   40.0    Estandar          9.5        1
22         23   90.000000   40.0    Estandar         12.5        2
23         24  110.000000   40.0    Estandar         12.0        3
24         25   87.000000   40.0    Estandar          5.5        2
25         26  113.000000   45.0         NaN         12.0        4
26         27   96.000000   45.0    Estandar         12.0        3
27         28   82.000000   45.0    Estandar         12.0        3
28         29  127.000000  100.0  Pura_Malta          8.5        4
29         30  160.000000  100.0  Pura_Malta         12.0        3
30         31   90.000000  100.0  Pura_Malta          NaN        4
31         32   86.090909  100.0  Pura_Malta         12.0        2
32         33  100.000000  100.0  Pura_Malta         10.0        3
33         34  100.000000    NaN  Pura_Malta         11.0        3
34         35   95.000000  100.0  Pura_Malta         12.0        0

In [8]:
#datos['Anejamiento'].fillna(7)
datos['pb']=datos['Precio']/datos['Anejamiento']
datos

    id_Whisky      Precio  Malta   Categoria  Anejamiento  Calidad         pb
0           1   70.000000   20.0        Lujo          5.0        3  14.000000
1           2   60.000000   20.0        Lujo          5.0        2  12.000000
2           3   65.000000   20.0        Lujo          7.5        2   8.666667
3           4   74.000000   25.0        Lujo          NaN        2        NaN
4           5   70.000000   25.0        Lujo         12.0        3   5.833333
5           6   86.090909   30.0        Lujo          5.0        0  17.218182
6           7   70.000000   30.0        Lujo          8.0        0   8.750000
7           8   55.000000   30.0        Lujo          5.0        2  11.000000
8           9   77.000000   30.0        Lujo          5.5        0  14.000000
9          10   93.000000   30.0        Lujo         12.0        0   7.750000
10         11   82.000000   30.0        Lujo         12.0        2   6.833333
11         12   73.000000   33.0    Estandar          6.5        1  11.230769
12         13   62.000000   33.0    Estandar          8.0        3   7.750000
13         14   87.000000   33.0    Estandar         12.0        3   7.250000
14         15   78.000000   35.0    Estandar         10.0        2   7.800000
15         16   73.000000   40.0    Estandar         10.5        4   6.952381
16         17   87.000000   40.0    Estandar          8.5        2  10.235294
17         18   80.000000   40.0         NaN          8.5        2   9.411765
18         19   85.000000   40.0    Estandar          9.5        2   8.947368
19         20   87.000000   40.0    Estandar          8.5        4  10.235294
20         21   80.000000   40.0    Estandar          9.5        2   8.421053
21         22   83.000000   40.0    Estandar          9.5        1   8.736842
22         23   90.000000   40.0    Estandar         12.5        2   7.200000
23         24  110.000000   40.0    Estandar         12.0        3   9.166667
24         25   87.000000   40.0    Estandar          5.5        2  15.818182
25         26  113.000000   45.0         NaN         12.0        4   9.416667
26         27   96.000000   45.0    Estandar         12.0        3   8.000000
27         28   82.000000   45.0    Estandar         12.0        3   6.833333
28         29  127.000000  100.0  Pura_Malta          8.5        4  14.941176
29         30  160.000000  100.0  Pura_Malta         12.0        3  13.333333
30         31   90.000000  100.0  Pura_Malta          NaN        4        NaN
31         32   86.090909  100.0  Pura_Malta         12.0        2   7.174242
32         33  100.000000  100.0  Pura_Malta         10.0        3  10.000000
33         34  100.000000    NaN  Pura_Malta         11.0        3   9.090909
34         35   95.000000  100.0  Pura_Malta         12.0        0   7.916667

In [9]:
etiq=['barato','medio','caro','muy caro']
columna = pd.cut(datos['Precio'],bins=len(etiq),labels=etiq)
datos['Precio2']=pd.Series.to_frame(columna)
datos

,id_Whisky,Precio,Malta,Categoria,Anejamiento,Calidad,pb,Precio2
0,1,70.000000,20.0,Lujo,5.0,3,14.000000,barato
1,2,60.000000,20.0,Lujo,5.0,2,12.000000,barato
2,3,65.000000,20.0,Lujo,7.5,2,8.666667,barato
3,4,74.000000,25.0,Lujo,NaN,2,NaN,barato
4,5,70.000000,25.0,Lujo,12.0,3,5.833333,barato
5,6,86.090909,30.0,Lujo,5.0,0,17.218182,medio
6,7,70.000000,30.0,Lujo,8.0,0,8.750000,barato
7,8,55.000000,30.0,Lujo,5.0,2,11.000000,barato
8,9,77.000000,30.0,Lujo,5.5,0,14.000000,barato
9,10,93.000000,30.0,Lujo,12.0,0,7.750000,medio
10,11,82.000000,30.0,Lujo,12.0,2,6.833333,medio
11,12,73.000000,33.0,Estandar,6.5,1,11.230769,barato
12,13,62.000000,33.0,Estandar,8.0,3,7.750000,barato
13,14,87.000000,33.0,Estandar,12.0,3,7.250000,medio
14,15,78.000000,35.0,Estandar,10.0,2,7.800000,barato
15,16,73.000000,40.0,Estandar,10.5,4,6.952381,barato
16,17,87.000000,40.0,Estandar,8.5,2,10.235294,medio
17,18,80.000000,40.0,NaN,8.5,2,9.411765,barato
18,19,85.000000,40.0,Estandar,9.5,2,8.947368,medio
19,20,87.000000,40.0,Estandar,8.5,4,10.235294,medio
20,21,80.000000,40.0,Estandar,9.5,2,8.421053,barato
21,22,83.000000,40.0,Estandar,9.5,1,8.736842,medio
22,23,90.000000,40.0,Estandar,12.5,2,7.200000,medio
23,24,110.000000,40.0,Estandar,12.0,3,9.166667,caro
24,25,87.000000,40.0,Estandar,5.5,2,15.818182,medio
25,26,113.000000,45.0,NaN,12.0,4,9.416667,caro
26,27,96.000000,45.0,Estandar,12.0,3,8.000000,medio
27,28,82.000000,45.0,Estandar,12.0,3,6.833333,medio
28,29,127.000000,100.0,Pura_Malta,8.5,4,14.941176,caro
29,30,160.000000,100.0,Pura_Malta,12.0,3,13.333333,muy caro
30,31,90.000000,100.0,Pura_Malta,NaN,4,NaN,medio
31,32,86.090909,100.0,Pura_Malta,12.0,2,7.174242,medio
32,33,100.000000,100.0,Pura_Malta,10.0,3,10.000000,medio
33,34,100.000000,NaN,Pura_Malta,11.0,3,9.090909,medio
34,35,95.000000,100.0,Pura_Malta,12.0,0,7.916667,medio

In [10]:
from sklearn.preprocessing  import LabelEncoder

numerizacion = LabelEncoder()
datos['Categoria']=numerizacion.fit_transform(datos['Categoria'])
datos

,id_Whisky,Precio,Malta,Categoria,Anejamiento,Calidad,pb,Precio2
0,1,70.000000,20.0,1,5.0,3,14.000000,barato
1,2,60.000000,20.0,1,5.0,2,12.000000,barato
2,3,65.000000,20.0,1,7.5,2,8.666667,barato
3,4,74.000000,25.0,1,NaN,2,NaN,barato
4,5,70.000000,25.0,1,12.0,3,5.833333,barato
5,6,86.090909,30.0,1,5.0,0,17.218182,medio
6,7,70.000000,30.0,1,8.0,0,8.750000,barato
7,8,55.000000,30.0,1,5.0,2,11.000000,barato
8,9,77.000000,30.0,1,5.5,0,14.000000,barato
9,10,93.000000,30.0,1,12.0,0,7.750000,medio
10,11,82.000000,30.0,1,12.0,2,6.833333,medio
11,12,73.000000,33.0,0,6.5,1,11.230769,barato
12,13,62.000000,33.0,0,8.0,3,7.750000,barato
13,14,87.000000,33.0,0,12.0,3,7.250000,medio
14,15,78.000000,35.0,0,10.0,2,7.800000,barato
15,16,73.000000,40.0,0,10.5,4,6.952381,barato
16,17,87.000000,40.0,0,8.5,2,10.235294,medio
17,18,80.000000,40.0,3,8.5,2,9.411765,barato
18,19,85.000000,40.0,0,9.5,2,8.947368,medio
19,20,87.000000,40.0,0,8.5,4,10.235294,medio
20,21,80.000000,40.0,0,9.5,2,8.421053,barato
21,22,83.000000,40.0,0,9.5,1,8.736842,medio
22,23,90.000000,40.0,0,12.5,2,7.200000,medio
23,24,110.000000,40.0,0,12.0,3,9.166667,caro
24,25,87.000000,40.0,0,5.5,2,15.818182,medio
25,26,113.000000,45.0,3,12.0,4,9.416667,caro
26,27,96.000000,45.0,0,12.0,3,8.000000,medio
27,28,82.000000,45.0,0,12.0,3,6.833333,medio
28,29,127.000000,100.0,2,8.5,4,14.941176,caro
29,30,160.000000,100.0,2,12.0,3,13.333333,muy caro
30,31,90.000000,100.0,2,NaN,4,NaN,medio
31,32,86.090909,100.0,2,12.0,2,7.174242,medio
32,33,100.000000,100.0,2,10.0,3,10.000000,medio
33,34,100.000000,NaN,2,11.0,3,9.090909,medio
34,35,95.000000,100.0,2,12.0,0,7.916667,medio

In [11]:
datos

,id_Whisky,Precio,Malta,Categoria,Anejamiento,Calidad,pb,Precio2
0,1,70.000000,20.0,1,5.0,3,14.000000,barato
1,2,60.000000,20.0,1,5.0,2,12.000000,barato
2,3,65.000000,20.0,1,7.5,2,8.666667,barato
3,4,74.000000,25.0,1,NaN,2,NaN,barato
4,5,70.000000,25.0,1,12.0,3,5.833333,barato
5,6,86.090909,30.0,1,5.0,0,17.218182,medio
6,7,70.000000,30.0,1,8.0,0,8.750000,barato
7,8,55.000000,30.0,1,5.0,2,11.000000,barato
8,9,77.000000,30.0,1,5.5,0,14.000000,barato
9,10,93.000000,30.0,1,12.0,0,7.750000,medio
10,11,82.000000,30.0,1,12.0,2,6.833333,medio
11,12,73.000000,33.0,0,6.5,1,11.230769,barato
12,13,62.000000,33.0,0,8.0,3,7.750000,barato
13,14,87.000000,33.0,0,12.0,3,7.250000,medio
14,15,78.000000,35.0,0,10.0,2,7.800000,barato
15,16,73.000000,40.0,0,10.5,4,6.952381,barato
16,17,87.000000,40.0,0,8.5,2,10.235294,medio
17,18,80.000000,40.0,3,8.5,2,9.411765,barato
18,19,85.000000,40.0,0,9.5,2,8.947368,medio
19,20,87.000000,40.0,0,8.5,4,10.235294,medio
20,21,80.000000,40.0,0,9.5,2,8.421053,barato
21,22,83.000000,40.0,0,9.5,1,8.736842,medio
22,23,90.000000,40.0,0,12.5,2,7.200000,medio
23,24,110.000000,40.0,0,12.0,3,9.166667,caro
24,25,87.000000,40.0,0,5.5,2,15.818182,medio
25,26,113.000000,45.0,3,12.0,4,9.416667,caro
26,27,96.000000,45.0,0,12.0,3,8.000000,medio
27,28,82.000000,45.0,0,12.0,3,6.833333,medio
28,29,127.000000,100.0,2,8.5,4,14.941176,caro
29,30,160.000000,100.0,2,12.0,3,13.333333,muy caro
30,31,90.000000,100.0,2,NaN,4,NaN,medio
31,32,86.090909,100.0,2,12.0,2,7.174242,medio
32,33,100.000000,100.0,2,10.0,3,10.000000,medio
33,34,100.000000,NaN,2,11.0,3,9.090909,medio
34,35,95.000000,100.0,2,12.0,0,7.916667,medio

In [12]:
from sklearn.preprocessing import MinMaxScaler

normalizador= MinMaxScaler() #creamos el tipo de normalización

datosANormalizar=datos['Anejamiento'] #seleccionamos la o las columnas a normalizar

datosANormalizar=datosANormalizar.values.reshape(len(datosANormalizar),1) #en caso de que sea una sola hay que redimensionarla

datosNormalizados= normalizador.fit_transform(datosANormalizar) #se aplica el normalizador

datos['Anejamiento']=datosNormalizados #nuevamente se agrega al Dataframe

In [13]:
datos

,id_Whisky,Precio,Malta,Categoria,Anejamiento,Calidad,pb,Precio2
0,1,70.000000,20.0,1,0.000000,3,14.000000,barato
1,2,60.000000,20.0,1,0.000000,2,12.000000,barato
2,3,65.000000,20.0,1,0.333333,2,8.666667,barato
3,4,74.000000,25.0,1,NaN,2,NaN,barato
4,5,70.000000,25.0,1,0.933333,3,5.833333,barato
5,6,86.090909,30.0,1,0.000000,0,17.218182,medio
6,7,70.000000,30.0,1,0.400000,0,8.750000,barato
7,8,55.000000,30.0,1,0.000000,2,11.000000,barato
8,9,77.000000,30.0,1,0.066667,0,14.000000,barato
9,10,93.000000,30.0,1,0.933333,0,7.750000,medio
10,11,82.000000,30.0,1,0.933333,2,6.833333,medio
11,12,73.000000,33.0,0,0.200000,1,11.230769,barato
12,13,62.000000,33.0,0,0.400000,3,7.750000,barato
13,14,87.000000,33.0,0,0.933333,3,7.250000,medio
14,15,78.000000,35.0,0,0.666667,2,7.800000,barato
15,16,73.000000,40.0,0,0.733333,4,6.952381,barato
16,17,87.000000,40.0,0,0.466667,2,10.235294,medio
17,18,80.000000,40.0,3,0.466667,2,9.411765,barato
18,19,85.000000,40.0,0,0.600000,2,8.947368,medio
19,20,87.000000,40.0,0,0.466667,4,10.235294,medio
20,21,80.000000,40.0,0,0.600000,2,8.421053,barato
21,22,83.000000,40.0,0,0.600000,1,8.736842,medio
22,23,90.000000,40.0,0,1.000000,2,7.200000,medio
23,24,110.000000,40.0,0,0.933333,3,9.166667,caro
24,25,87.000000,40.0,0,0.066667,2,15.818182,medio
25,26,113.000000,45.0,3,0.933333,4,9.416667,caro
26,27,96.000000,45.0,0,0.933333,3,8.000000,medio
27,28,82.000000,45.0,0,0.933333,3,6.833333,medio
28,29,127.000000,100.0,2,0.466667,4,14.941176,caro
29,30,160.000000,100.0,2,0.933333,3,13.333333,muy caro
30,31,90.000000,100.0,2,NaN,4,NaN,medio
31,32,86.090909,100.0,2,0.933333,2,7.174242,medio
32,33,100.000000,100.0,2,0.666667,3,10.000000,medio
33,34,100.000000,NaN,2,0.800000,3,9.090909,medio
34,35,95.000000,100.0,2,0.933333,0,7.916667,medio